### ISSUE TITLE
JSON::Validator version compatibility issue

### ISSUE THREAD

**Issue by sirtoobii** [oetiker/callbackery#128]
With the release of JSON::Validator [3.23](https://github.com/mojolicious/json-validator/commit/a94acf3d944faa6160f64b13bc21b70947d47aca) it becomes dependent on `List::Util 'uniq'` which in turn requires `List::Util >= 1.45`. However, this version only shipped from `perl >= 5.26`

I suggest either increasing the perl version in `Makefile.PL`(probably not desired) or lock the the dependency `JSON::Validator` to version `3.22`

**Comment by oetiker** [comment]
hmmm so what happens when installing on 5.22, doesn't just a current List::Util get installed ?

**Comment by sirtoobii** [comment]
Apparently not. I've tried both `5.22` and `5.24`. Also if you check [https://perldoc.perl.org/List::Util](https://perldoc.perl.org/List::Util) `uniq` is only apparent in versions >= 5.26

**Comment by oetiker** [comment]
ah, this is the 'core' version of List::Util ... there is also the non core version https://metacpan.org/pod/List::Util if the core version has too low a version, an update from cpan will be installed ... this should happen automatically ...

**Comment by sirtoobii** [comment]
Well, it seem that this issue is an infamous _layer 8_ problem, resulting from multiple perl versions installed at the same time...
