### ISSUE TITLE
MISSING_PERL_MODULES, wrong detection

### ISSUE THREAD

**Issue by ghost** [oetiker/callbackery#15]
In Makefile:
```
MISSING_PERL_MODULES =  Mojolicious@6.33 Mojo::SQLite@0.018
```

but I do have:
```
$ sudo cpanm Mojo::SQLite
Mojo::SQLite is up to date. (0.019)
```
and I have:
```
$ sudo cpanm Mojolicious
Mojolicious is up to date. (6.39)
```

The script, ./configure or which one exactly, shall properly detect the installed modules. I have changed in ./configure the version number, to continue with installation for myself.

Later I run:
```
./configure --prefix=$HOME/public_html/callbakery/cb_demo --with-qooxdoo-sdk-dir=$HOME/public_html/callbakery/qooxdoo-5.0.1-sdk
```

and I got this error:
```
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/home/data1/protected/public_html/callbakery/cb_demo/lib'
 /bin/mkdir -p '/home/data1/protected/public_html/callbakery/cb_demo/lib/CbDemo/GuiPlugin'
 /usr/bin/install -c -m 644  ./CbDemo/GuiPlugin/SongForm.pm ./CbDemo/GuiPlugin/Song.pm '/home/data1/protected/public_html/callbakery/cb_demo/lib/CbDemo/GuiPlugin'
/usr/bin/install: ‘./CbDemo/GuiPlugin/SongForm.pm’ and ‘/home/data1/protected/public_html/callbakery/cb_demo/lib/CbDemo/GuiPlugin/SongForm.pm’ are the same file
/usr/bin/install: ‘./CbDemo/GuiPlugin/Song.pm’ and ‘/home/data1/protected/public_html/callbakery/cb_demo/lib/CbDemo/GuiPlugin/Song.pm’ are the same file
Makefile:259: recipe for target 'install-nobase_dataDATA' failed
```
And when I run:
```
make -i install
```
I could see many others "are the same file" errors.

**Comment by oetiker** [comment]
make sure to pick a install directory distinct from the directory you unpacked your source ... my suggestion is to follow the instructions ... also there is no reason to put anything into public_html at all ... mojolicious has a builtin webserver ... if you want to interface with apache you would access the mojolicious app via a reverse proxy link

**Comment by rmaddox** [comment]
The ./configure script tries to copy some files multiple times.
My directory is distinct from first one, and I could bring it to run with: make -i install.

Now, I am trying to figure out if it can simply connect to existing gedafe database, but I guess installation instructions are not yet finished.

**Comment by oetiker** [comment]
callbackery is NOT gedafe ... read the docs ... the gedafe part is work in progress and not published yet

**Comment by rmaddox** [comment]
sure, sure, I was just thinking it will get a hook on existing Gedafe databases in future, it looks like it is not yet there. Thank you

**Comment by oetiker** [comment]
please check out 0.6.4
