### ISSUE TITLE
Push updates to frontend

### ISSUE THREAD

**Issue by zmughal** [oetiker/callbackery#177]
I'm not sure where to ask this question, but I'm relatively new to Qooxdoo and trying out CallBackery.

I was wondering if there is a way to use CallBackery to send updates as the backend does other things. For example, a long-running series of tasks and as each task completes, update a specific row of a table widget, then when all are finished, enable a button. I would want to do this without having the user hit a "Refresh data" button.

Usually I would use a WebSocket with Mojolicious for this.

**Comment by oetiker** [comment]
There is an pseudo action button which reloads a form at regula intervals ... at the moment there is no web socket option.
