### ISSUE TITLE
No Table Refresh after Upload

### ISSUE THREAD

**Issue by samoser** [oetiker/callbackery#22]
My tab is based on an AbstractTable and shows a list of uploaded files. 
It has an upload button where its handler returns `action => 'dataModified',`.
After an upload, the backend gets the new file as well, but the frontend does not show it.

**Comment by oetiker** [comment]
you should set 'reload' as a response from the action

**Comment by samoser** [comment]
Thanks mate. Unfortunately, that didn't change the behaviour.
