### ISSUE TITLE
Table: Row selection not persisting

### ISSUE THREAD

**Issue by samoser** [oetiker/callbackery#23]
My Tab is based on AbstractTable.
When I select a row
![image](https://cloud.githubusercontent.com/assets/16583675/16419999/f777d5a0-3d4f-11e6-93a3-a97e87463f05.png)
and show some details by clicking the appropriate button (with `btnCfg->{options}{noReload} => 1`, after closing that form, the row selection is lost.
![image](https://cloud.githubusercontent.com/assets/16583675/16420130/7c30e48a-3d50-11e6-9e9e-35869dce31d0.png)
The row is still marked with some grey, but the blue is on row 1, which will be used for the next detail showing, which is not nice for me.

**Comment by oetiker** [comment]
fixed in v0.6.4 if you defined the primary property on the primary key
