### ISSUE TITLE
Table: useless default selection

### ISSUE THREAD

**Issue by samoser** [oetiker/callbackery#24]
My tab is based on AbstractTable. 
I introduce a SelectBox to select different data source.
When I select one, the first row is marked blue:
![image](https://cloud.githubusercontent.com/assets/16583675/16420314/271eaba2-3d51-11e6-8298-f6c100a34535.png)
But there is no selection: `'selection' => {},`.
It would be nice if there is NO blue row or if the blue row also selects data.
_(by the way: it works without this SelectBox, when it just has one data source to show)_

**Comment by oetiker** [comment]
fixed  in v0.6.4
