### ISSUE TITLE
New Widget #1 (for formCfg)

### ISSUE THREAD

**Issue by samoser** [oetiker/callbackery#34]
Currently there is no nice way to add a description in formCfg. Would you please implement such a widget?

**Comment by oetiker** [comment]
does the 'note' property not help ? it allows to provide a per widget description as well as one section by using adding it to a title widget

**Comment by samoser** [comment]
Sorry, I mean the formCfg in a Table

**Comment by oetiker** [comment]
render notes in hbar form type

**Comment by oetiker** [comment]
v0.9.0 supports this
