### ISSUE TITLE
New Widget #2 (for formCfg)

### ISSUE THREAD

**Issue by samoser** [oetiker/callbackery#35]
Currently there is no nice way to add a separation in formCfg. Would you please implement such a widget?

**Comment by oetiker** [comment]
you mean a separation without a title ?

**Comment by samoser** [comment]
Yes, like a larger space (like here in the formatting bar) or something like a pipe

**Comment by oetiker** [comment]
add separator bar in hbar renderer for section widget

**Comment by oetiker** [comment]
checkout out 'separator' psuedo action in v0.9.0
