### ISSUE TITLE
placeholder is not translated

### ISSUE THREAD

**Issue by samoser** [oetiker/callbackery#42]
In my implementation of formCfg (of an AbstractTable) I use a text widget with a placeholder. That placeholder is not translated. Would you mind checking this?
```
    }
    ...
    widget => 'text',
    set => {
        placeholder => trm('ERP_ID'),
        liveUpdate => $self->true
    },
```
Thank you, mate!

**Comment by oetiker** [comment]
try e96a531

**Comment by samoser** [comment]
You are my hero of the day!
